apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-web-app-deploy
  labels:
    app: bankapp-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bankapp-web-app
  template:
    metadata:
      labels:
        app: bankapp-web-app
    spec:
      containers:
      - name: bankapp-web-container
        image: prajaktak19/bankapp-web-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: bankapp-web-app-np-service1
  labels:
    app: bankapp-web-app
spec:
  selector:
    app: bankapp-web-app

  type: NodePort
  ports:
  - nodePort: 31111    
    port: 8081
    targetPort: 8081
